### ISSUE TITLE
Error with python2 -m pip install pycups==1.9.74

### ISSUE THREAD

**Issue by rickrich** [OpenPrinting/pycups#23]
$ python2 -m pip install pycups==1.9.74
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pycups==1.9.74
  Using cached https://files.pythonhosted.org/packages/00/ce/836a0deb8b24bcd5f850f8fb97f99fb4abd7374e078b9e6df5a0838f8eb5/pycups-1.9.74.tar.bz2
Installing collected packages: pycups
  Running setup.py install for pycups ... error
    ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-Bs7apZ/pycups/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-msfD6t/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'cups' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DVERSION="1.9.74" -I/usr/include/python2.7 -c cupsmodule.c -o build/temp.linux-x86_64-2.7/cupsmodule.o
    gcc: fatal error: cannot read spec file ‘/usr/lib/rpm/redhat/redhat-hardened-cc1’: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-Bs7apZ/pycups/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-msfD6t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Bs7apZ/pycups/

**Comment by zdohnal** [comment]
Hi Rick,

what OS and its version do you use? IIRC Fedora is mostly python3 only since F30.

Either way, it looks like either pip or gcc is setting some default compilation flags, which you don't have available. pycups doesn't set any of those CFLAGS.

You can find out which package brings in the file which causes the error - via ```dnf repoquery --whatprovides```, install it and see if it helps.

If it doesn't, you can ask for help on Fedora mailing lists/IRC, because it doesn't seem to be a problem specific to pycups.

**Comment by rickrich** [comment]
Fedora Cinnamon 31

# dnf repoquery --whatprovides
Command line error: argument --whatprovides: expected one argument

Also, if I use python3 (but python2 is what I want):

$ sudo python3 -m pip install pycups==1.9.74
Collecting pycups==1.9.74
  Using cached pycups-1.9.74.tar.bz2 (52 kB)
Using legacy setup.py install for pycups, since package 'wheel' is not installed.
Installing collected packages: pycups
  Attempting uninstall: pycups
    Found existing installation: pycups 2.0.1
ERROR: Cannot uninstall 'pycups'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by zdohnal** [comment]
> dnf repoquery --whatprovides
> Command line error: argument --whatprovides: expected one argument

I expected that you'll provide the filename which you got the error before. It needs an absolute (or its regexp) path of file you want to find - see man pages.

> 
> Also, if I use python3 (but python2 is what I want):
> 
> $ sudo python3 -m pip install pycups==1.9.74
> Collecting pycups==1.9.74
> Using cached pycups-1.9.74.tar.bz2 (52 kB)
> Using legacy setup.py install for pycups, since package 'wheel' is not installed.
> Installing collected packages: pycups
> Attempting uninstall: pycups
> Found existing installation: pycups 2.0.1
> ERROR: Cannot uninstall 'pycups'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

I'm not a pypi expert, but it seems you have already pycups installed, in its version 2.0.1 - probably as a OS package.

**Comment by zdohnal** [comment]
And I would like to mention python 2 is obsoleted and no longer supported since 1st Jan 2020.

**Comment by rickrich** [comment]
I used:

https://sourceforge.net/projects/g-manual-duplex/files/pycups-binary-lib64.tar.gz/

And got it installed:
-rwxrwxr-x root/root    593456 2019-10-31 13:32 /usr/lib64/python2.7/site-packages/cups.so

The module pip does not work.
