### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by carstenblt** [OpenPrinting/pycups#27]
Is there any documentation available online?

I am really about to give up on this package... `make doc` doesn't compile on MacOS at all out of the box, on a linux box I first tried it with python3 until I realized that epydoc doesn't work with python3. Then I tried compiling for python2, which again didn't work...

**Comment by zdohnal** [comment]
Hi,

I'm sorry I overlooked the project is still using epydoc in spec file for generating docs. Now it uses pydoc, please check ```make doc``` again.
