### ISSUE TITLE
[Feature Request] Allow connecting via Unix Domain Socket

### ISSUE THREAD

**Issue by philomory** [OpenPrinting/pycups#33]
It'd be nice if we could connect to the CUPS server via a unix domain socket such as `/var/run/cups/cups.sock`.

**Comment by zdohnal** [comment]
Hi @philomory ,

AFAIK it is possible to connect via an Unix domain socket right now - function ```Connection_init()``` uses ```cupsServer()``` function, which can return hostname, address or domain socket. It depends on your CUPS setup which one is returned from ```cupsServer()``` and then used during setting up connections in pycups.

See comment about ```cupsServer()``` in ```cups/usersys.c```.
