### ISSUE TITLE
Forgetten .gitignore file

### ISSUE THREAD

**Issue by usta** [OpenPrinting/pycups#39]
It will be nice to have a .gitignore file so PRs wont get .so or similar not needed files. ( for example : #4 ) 
It looks like this one is suitable for this project : 
https://www.toptal.com/developers/gitignore/api/python,c,c++

**Comment by zdohnal** [comment]
Fixed by commit https://github.com/OpenPrinting/pycups/commit/a983b58aa66c0e93055e79e9359ec81d2c6d8f3b
