### ISSUE TITLE
Ubuntu VM with Cups Server and docker container with pycups: cups.IPPError: (1030, 'The printer or class does not exist.')

### ISSUE THREAD

**Issue by PoKeRGT** [OpenPrinting/pycups#56]
First of all,
Sorry if this does not really belong here but I'm a little desperate about this.

As the title says I have a Ubuntu VM with the CUPS Server and Docker.
Inside one container I have a little python flask app that uses pycups to send print requests to the outside CUPS Server.
It does not work. The error message is always 

`cups.IPPError: (1030, 'The printer or class does not exist.')`

This same app directly run in the Ubuntu VM works perfectly.

I have a post in stackoverflow with more info:
[https://stackoverflow.com/questions/77233067/ubuntu-vm-with-cups-server-and-docker-container-with-pycups-cups-ipperror-103](https://stackoverflow.com/questions/77233067/ubuntu-vm-with-cups-server-and-docker-container-with-pycups-cups-ipperror-103)

Please...HELP!

PD: Feel free to delete this issue, as it's only a desperate try to get more attention to my problem and I don't know where else to get help

**Comment by nkrumm** [comment]
This seems similar to the issue and fixes proposed here: https://github.com/OpenPrinting/pycups/issues/30

**Comment by zdohnal** [comment]
@PoKeRGT do the comments from #30 work for you?

**Comment by PoKeRGT** [comment]
Sorry, that project is over and working outside of the VM.
