### ISSUE TITLE
Please release 1.9.74 with the fixes for writeRequestData!!

### ISSUE THREAD

**Issue by mbello** [OpenPrinting/pycups#6]
The 1.9.74 release is mentioned on the NEWS file but it never happened.

Would the maintainer please do it?

**Comment by mbello** [comment]
Ok, but right now there is a broken functionality that is fixed already on head and do not see a reason why you cannot push it to 1.9.74 and avoid people wasting many hours like I did.

**THIS DOES NOT WORK ON 1.9.73**
id = conn.createJob(printer_name, 'JOB NAME', {})
conn.startDocument(printer_name, id, 'DOC NAME',  cups.CUPS_FORMAT_PDF, 1)
# now we will call the buggy function
conn.writeRequestData(pdf_binary, len(pdf_binary))
conn.finishDocument(printer_name)

**Instead I am forced to write a temp file to disk and print in this way:**
with tempfile.NamedTemporaryFile(suffix='.pdf') as tf:
    tf.write(pdf_binary)
    tf.flush()
    conn.printFile(printer_name, tf.name, "xpto", {})

Could you please release a new version so that we can have the "writeRequestData" shipped?

**Comment by zdohnal** [comment]
I would recommend you to calm down. I released new version.
